version: "3"
services:

  pgadmin:
    ports:
      - "5050:5050"

  backend:
    ports:
      - '80:80'
    expose:
      - '80'
    environment:
      - SERVER_HOST=http://${DOMAIN}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh
